In [4]:
import numpy as np

In [5]:
a= np.array([[.75,.1,.1],[.1,.6,.2],[.15,.3,.7]])

In [6]:
a**10

array([[5.63135147e-02, 1.00000000e-10, 1.00000000e-10],
       [1.00000000e-10, 6.04661760e-03, 1.02400000e-07],
       [5.76650391e-09, 5.90490000e-06, 2.82475249e-02]])

In [8]:
eigenvalues, eigenvectors=np.linalg.eig(a)

In [9]:
eigenvalues

array([0.65, 1.  , 0.4 ])

In [12]:
eigenvectors.round(3)

array([[-0.811,  0.485, -0.   ],
       [ 0.324,  0.485, -0.707],
       [ 0.487,  0.728,  0.707]])